import type { TourPackage } from "./types";

export const sampleTours: TourPackage[] = [
  {
    id: "1",
    title: "Ultimate Gorilla Trekking Adventure",
    destination: "Uganda",
    duration: 5,
    price: 2450,
    currency: "USD",
    rating: 4.9,
    reviewCount: 127,
    images: [
      "https://ik.imagekit.io/54hg3nvcfg/greg-gollin-i3srrRDsJEs-unsplash.jpg?updatedAt=1752095892120",
    ],
    highlights: [
      "Mountain gorilla encounters in Bwindi Forest",
      "Expert local guides and trackers",
      "Luxury eco-lodge accommodation",
      "Cultural village visits",
      "All permits and transfers included",
    ],
    tourOperator: {
      name: "Uganda Safari Co.",
      logo: "https://ik.imagekit.io/54hg3nvcfg/Icons/syncplicity_873148.png?updatedAt=1752097575545",
    },
    accommodationType: "Luxury",
    groupSize: "Small group",
    difficulty: "Moderate",
    category: "Gorilla trekking",
  },
  {
    id: "2",
    title: "Serengeti Great Migration Safari",
    destination: "Tanzania",
    duration: 7,
    price: 3200,
    currency: "USD",
    rating: 4.8,
    reviewCount: 89,
    images: [
      "https://ik.imagekit.io/54hg3nvcfg/dawn-westveld-FmUx8z_Tz4A-unsplash.jpg?updatedAt=1752096189254"
    ],
    highlights: [
      "Witness the Great Migration",
      "Big Five game viewing",
      "Hot air balloon safari",
      "Ngorongoro Crater exploration",
      "Professional photography guide",
    ],
    tourOperator: {
      name: "Serengeti Expeditions",
      logo: "https://ik.imagekit.io/54hg3nvcfg/Icons/aeon_16147203.png?updatedAt=1752097575723",
    },
    accommodationType: "Luxury",
    groupSize: "Private",
    difficulty: "Easy",
    category: "Wildlife",
  },
  {
    id: "3",
    title: "Masai Mara Budget Safari",
    destination: "Kenya",
    duration: 4,
    price: 680,
    currency: "USD",
    rating: 4.3,
    reviewCount: 156,
    images: ["https://ik.imagekit.io/54hg3nvcfg/michael-rodock-jsTYuhX5LX4-unsplash.jpg?updatedAt=1752096434113"],
    highlights: [
      "Game drives in Masai Mara",
      "Camping under the stars",
      "Masai cultural experience",
      "All meals included",
      "Shared transportation",
    ],
    tourOperator: {
      name: "Kenya Adventures",
      logo: "https://ik.imagekit.io/54hg3nvcfg/Icons/Eagle%20Head%20Sideview%20Design.png?updatedAt=1752098707626",
    },
    accommodationType: "Budget",
    groupSize: "Large group",
    difficulty: "Easy",
    category: "Wildlife",
  },
  {
    id: "4",
    title: "Rwanda Gorillas & Golden Monkeys",
    destination: "Rwanda",
    duration: 6,
    price: 2800,
    currency: "USD",
    rating: 4.7,
    reviewCount: 94,
    images: ["https://ik.imagekit.io/54hg3nvcfg/vg-bingi-wuxuh3xJKFg-unsplash.jpg?updatedAt=1752096469372"],
    highlights: [
      "Mountain gorilla trekking",
      "Golden monkey tracking",
      "Volcanoes National Park",
      "Kigali city tour",
      "Genocide memorial visit",
    ],
    tourOperator: {
      name: "Rwanda Eco Tours",
      logo: "https://ik.imagekit.io/54hg3nvcfg/Icons/C%20Letter%20Red.png?updatedAt=1752098290838",
    },
    accommodationType: "Mid-range",
    groupSize: "Small group",
    difficulty: "Moderate",
    category: "Gorilla trekking",
  },
  {
    id: "5",
    title: "Botswana Okavango Delta Safari",
    destination: "Botswana",
    duration: 8,
    price: 4500,
    currency: "USD",
    rating: 4.9,
    reviewCount: 67,
    images: ["https://ik.imagekit.io/54hg3nvcfg/wynand-uys-4ZCA3xukIso-unsplash.jpg?updatedAt=1752096591244"],
    highlights: [
      "Mokoro canoe excursions",
      "Luxury tented camps",
      "Helicopter scenic flights",
      "Big Five encounters",
      "Professional guide throughout",
    ],
    tourOperator: {
      name: "Okavango Specialists",
      logo: "https://ik.imagekit.io/54hg3nvcfg/Icons/S%20Letter.png?updatedAt=1752098291250",
    },
    accommodationType: "Luxury",
    groupSize: "Private",
    difficulty: "Easy",
    category: "Wildlife",
  },
  {
    id: "6",
    title: "Cultural Heritage Tour Uganda",
    destination: "Uganda",
    duration: 10,
    price: 1850,
    currency: "USD",
    rating: 4.5,
    reviewCount: 73,
    images: ["https://ik.imagekit.io/54hg3nvcfg/ransford-quaye-RCAUud6Wcmo-unsplash.jpg?updatedAt=1752096609203"],
    highlights: [
      "Traditional village stays",
      "Local craft workshops",
      "Cultural performances",
      "Historical site visits",
      "Community-based tourism",
    ],
    tourOperator: {
      name: "Cultural Safaris Uganda",
      logo: "https://ik.imagekit.io/54hg3nvcfg/Icons/Chameleon.png?updatedAt=1752098291246",
    },
    accommodationType: "Mid-range",
    groupSize: "Small group",
    difficulty: "Easy",
    category: "Cultural",
  },
  {
    id: "7",
    title: "Mount Kilimanjaro Climbing Safari",
    destination: "Tanzania",
    duration: 12,
    price: 3800,
    currency: "USD",
    rating: 4.6,
    reviewCount: 112,
    images: ["https://ik.imagekit.io/54hg3nvcfg/john-njoroge-PaGyC5KPm3M-unsplash.jpg?updatedAt=1752096974298"],
    highlights: [
      "Summit Africa's highest peak",
      "Machame route ascent",
      "Professional mountain guides",
      "All equipment provided",
      "Post-climb safari extension",
    ],
    tourOperator: {
      name: "Kilimanjaro Experts",
      logo: "https://ik.imagekit.io/54hg3nvcfg/Icons/_Pngtree_give%20me%20random%20company%20logo_20874271.png?updatedAt=1752098292525",
    },
    accommodationType: "Mid-range",
    groupSize: "Small group",
    difficulty: "Challenging",
    category: "Adventure",
  },
  {
    id: "8",
    title: "South Africa Garden Route",
    destination: "South Africa",
    duration: 9,
    price: 2200,
    currency: "USD",
    rating: 4.4,
    reviewCount: 88,
    images: ["https://ik.imagekit.io/54hg3nvcfg/savannah-koomen-Wbt0cD840S0-unsplash.jpg?updatedAt=1752097039446"],
    highlights: [
      "Cape Town to Port Elizabeth",
      "Wine tasting experiences",
      "Whale watching opportunities",
      "Scenic coastal drives",
      "Luxury accommodations",
    ],
    tourOperator: {
      name: "South African Tours",
      logo: "https://ik.imagekit.io/54hg3nvcfg/Icons/SVG%20Firestorm%20Flame.png?updatedAt=1752098449921",
    },
    accommodationType: "Luxury",
    groupSize: "Private",
    difficulty: "Easy",
    category: "Cultural",
  },
];
