import type { TourPackage } from "./types"

export const sampleTours: TourPackage[] = [
  {
    id: "1",
    title: "Ultimate Gorilla Trekking Adventure",
    destination: "Uganda",
    duration: 5,
    price: 2450,
    currency: "USD",
    rating: 4.9,
    reviewCount: 127,
    images: ["/placeholder.svg?height=400&width=600"],
    highlights: [
      "Mountain gorilla encounters in Bwindi Forest",
      "Expert local guides and trackers",
      "Luxury eco-lodge accommodation",
      "Cultural village visits",
      "All permits and transfers included",
    ],
    tourOperator: {
      name: "Uganda Safari Co.",
      logo: "/placeholder.svg?height=40&width=40",
    },
    accommodationType: "Luxury",
    groupSize: "Small group",
    difficulty: "Moderate",
    category: "Gorilla trekking",
  },
  {
    id: "2",
    title: "Serengeti Great Migration Safari",
    destination: "Tanzania",
    duration: 7,
    price: 3200,
    currency: "USD",
    rating: 4.8,
    reviewCount: 89,
    images: ["/placeholder.svg?height=400&width=600"],
    highlights: [
      "Witness the Great Migration",
      "Big Five game viewing",
      "Hot air balloon safari",
      "Ngorongoro Crater exploration",
      "Professional photography guide",
    ],
    tourOperator: {
      name: "Serengeti Expeditions",
      logo: "/placeholder.svg?height=40&width=40",
    },
    accommodationType: "Luxury",
    groupSize: "Private",
    difficulty: "Easy",
    category: "Wildlife",
  },
  {
    id: "3",
    title: "Masai Mara Budget Safari",
    destination: "Kenya",
    duration: 4,
    price: 680,
    currency: "USD",
    rating: 4.3,
    reviewCount: 156,
    images: ["/placeholder.svg?height=400&width=600"],
    highlights: [
      "Game drives in Masai Mara",
      "Camping under the stars",
      "Masai cultural experience",
      "All meals included",
      "Shared transportation",
    ],
    tourOperator: {
      name: "Kenya Adventures",
      logo: "/placeholder.svg?height=40&width=40",
    },
    accommodationType: "Budget",
    groupSize: "Large group",
    difficulty: "Easy",
    category: "Wildlife",
  },
  {
    id: "4",
    title: "Rwanda Gorillas & Golden Monkeys",
    destination: "Rwanda",
    duration: 6,
    price: 2800,
    currency: "USD",
    rating: 4.7,
    reviewCount: 94,
    images: ["/placeholder.svg?height=400&width=600"],
    highlights: [
      "Mountain gorilla trekking",
      "Golden monkey tracking",
      "Volcanoes National Park",
      "Kigali city tour",
      "Genocide memorial visit",
    ],
    tourOperator: {
      name: "Rwanda Eco Tours",
      logo: "/placeholder.svg?height=40&width=40",
    },
    accommodationType: "Mid-range",
    groupSize: "Small group",
    difficulty: "Moderate",
    category: "Gorilla trekking",
  },
  {
    id: "5",
    title: "Botswana Okavango Delta Safari",
    destination: "Botswana",
    duration: 8,
    price: 4500,
    currency: "USD",
    rating: 4.9,
    reviewCount: 67,
    images: ["/placeholder.svg?height=400&width=600"],
    highlights: [
      "Mokoro canoe excursions",
      "Luxury tented camps",
      "Helicopter scenic flights",
      "Big Five encounters",
      "Professional guide throughout",
    ],
    tourOperator: {
      name: "Okavango Specialists",
      logo: "/placeholder.svg?height=40&width=40",
    },
    accommodationType: "Luxury",
    groupSize: "Private",
    difficulty: "Easy",
    category: "Wildlife",
  },
  {
    id: "6",
    title: "Cultural Heritage Tour Uganda",
    destination: "Uganda",
    duration: 10,
    price: 1850,
    currency: "USD",
    rating: 4.5,
    reviewCount: 73,
    images: ["/placeholder.svg?height=400&width=600"],
    highlights: [
      "Traditional village stays",
      "Local craft workshops",
      "Cultural performances",
      "Historical site visits",
      "Community-based tourism",
    ],
    tourOperator: {
      name: "Cultural Safaris Uganda",
      logo: "/placeholder.svg?height=40&width=40",
    },
    accommodationType: "Mid-range",
    groupSize: "Small group",
    difficulty: "Easy",
    category: "Cultural",
  },
  {
    id: "7",
    title: "Mount Kilimanjaro Climbing Safari",
    destination: "Tanzania",
    duration: 12,
    price: 3800,
    currency: "USD",
    rating: 4.6,
    reviewCount: 112,
    images: ["/placeholder.svg?height=400&width=600"],
    highlights: [
      "Summit Africa's highest peak",
      "Machame route ascent",
      "Professional mountain guides",
      "All equipment provided",
      "Post-climb safari extension",
    ],
    tourOperator: {
      name: "Kilimanjaro Experts",
      logo: "/placeholder.svg?height=40&width=40",
    },
    accommodationType: "Mid-range",
    groupSize: "Small group",
    difficulty: "Challenging",
    category: "Adventure",
  },
  {
    id: "8",
    title: "South Africa Garden Route",
    destination: "South Africa",
    duration: 9,
    price: 2200,
    currency: "USD",
    rating: 4.4,
    reviewCount: 88,
    images: ["/placeholder.svg?height=400&width=600"],
    highlights: [
      "Cape Town to Port Elizabeth",
      "Wine tasting experiences",
      "Whale watching opportunities",
      "Scenic coastal drives",
      "Luxury accommodations",
    ],
    tourOperator: {
      name: "South African Tours",
      logo: "/placeholder.svg?height=40&width=40",
    },
    accommodationType: "Luxury",
    groupSize: "Private",
    difficulty: "Easy",
    category: "Cultural",
  },
]
